### ISSUE TITLE
Moving away from the Buffer constructor

### ISSUE THREAD

**Issue by gabrielschulhof** [ARMmbed/cbor-sync#1]
The Buffer constructor is unsafe and deprecated. It appears in [a few places](https://github.com/ARMmbed/cbor-sync/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22) in this repo. Could you please move to `Buffer.from()` instead of using the constructor?

**Comment by thegecko** [comment]
PRs very welcome ;)
